[package]
name = "mcp_server_tavily"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/mcp_server_tavily.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
zed_extension_api = "0.6.0"
schemars = "0.8"
