id = "mcp-server-tavily"
name = "Tavily MCP Server"
description = "Model Context Protocol Server for Tavily"
version = "0.0.2"
schema_version = 1
authors = ["Chlorodose <chlorodose@chlorodose.me>"]
repository = "https://github.com/chlorodose/zed-mcp-server-tavily"

[context_servers.mcp-server-tavily]
name = "Tavily MCP Server"
